name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push frontend Docker image
      run: |
        docker build -f Docker/frontend.Dockerfile -t myapp-frontend:latest .
        docker push myapp-frontend:latest

    - name: Build and push backend Docker image
      run: |
        docker build -f Docker/backend.Dockerfile -t myapp-backend:latest .
        docker push myapp-backend:latest

    - name: Build and push AI Docker image
      run: |
        docker build -f Docker/ai.Dockerfile -t myapp-ai:latest .
        docker push myapp-ai:latest

    - name: Deploy to Kubernetes
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'
      
    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/ingress.yaml
