// src/redux/actions/actionTypes.ts
export const FETCH_OFFICERS_REQUEST = 'FETCH_OFFICERS_REQUEST';
export const FETCH_OFFICERS_SUCCESS = 'FETCH_OFFICERS_SUCCESS';
export const FETCH_OFFICERS_FAILURE = 'FETCH_OFFICERS_FAILURE';

export const FETCH_CLIENTS_REQUEST = 'FETCH_CLIENTS_REQUEST';
export const FETCH_CLIENTS_SUCCESS = 'FETCH_CLIENTS_SUCCESS';
export const FETCH_CLIENTS_FAILURE = 'FETCH_CLIENTS_FAILURE';


export const FETCH_GUARDS_REQUEST = 'FETCH_GUARDS_REQUEST';
export const FETCH_GUARDS_SUCCESS = 'FETCH_GUARDS_SUCCESS';
export const FETCH_GUARDS_FAILURE = 'FETCH_GUARDS_FAILURE';