openapi: 3.0.0
info:
  title: MirazSec API
  description: API documentation for MirazSec
  version: 1.0.0
paths:
  /notifications:
    post:
      summary: Create a new notification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                message:
                  type: string
      responses:
        '201':
          description: Notification created
        '500':
          description: Server error
